[dev]
  command = "astro dev"
  targetPort = 4321
  port = 8888
  framework = "#custom"

[[redirects]]
  from = "/api/hits"
  to = "/.netlify/functions/hit-counter"
  status = 200

[[redirects]]
  from = "/api/guestbook"
  to = "/.netlify/functions/guestbook-read"
  status = 200
